version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: my-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: openairlines
      MARIADB_USER: openairlines
      MARIADB_PASSWORD: "*I3I;8D985Sd"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
